### ISSUE TITLE
Im pretending to file a lawsuit~

### ISSUE THREAD

**Issue by glixxzzy** [Gl1xzzy/blooket-hack#142]
Go report me pls

**Comment by Gl1xzzy** [comment]
![Screenshot 2022-06-18 12 54 56 AM](https://user-images.githubusercontent.com/107596027/174423437-d2bdb35e-5fdb-4df3-bc1e-4e1d99ecd7a9.png)
:)

**Comment by Gl1xzzy** [comment]
![Screenshot 2022-06-18 12 58 30 AM](https://user-images.githubusercontent.com/107596027/174423483-6808c8cd-a1eb-4212-b238-306cd9683e58.png)
;)
