### ISSUE TITLE
You realize stealing my hacks AND changing the license doesn't do anything.. Right?

### ISSUE THREAD

**Issue by glixxzzy** [Gl1xzzy/blooket-hack#4]
I hope you know I will never use ANY numbers in my name and I will be taking legal action (contacting a lawyer) if this fake profile is not taken down within 48 hours!

Sincerely, yours truely
-lol-jude

**Comment by Gl1xzzy** [comment]
Ok I didn't steal your hacks.
And your lol-jude.

**Comment by glixxzzy** [comment]
I am going to be filing for Cease and Desist and I will file for a law suit.

**Comment by glixxzzy** [comment]
You fork my repo and then copy your fork I've seen what you did even to my website skull 💀
