### ISSUE TITLE
Hello! This is Gliz's lawyer!

### ISSUE THREAD

**Issue by glixxzzy** [Gl1xzzy/blooket-hack#5]
Please comment your email below or else this will turn into a lawsuit! This is currently your last warning and a Cease and Desist. Failure to comply WILL result in you being required to show up to court!

**Comment by glixxzzy** [comment]
Also, if you continue this action of editing the comments to make my client look fake you WILL be required to show in court as Gliz will be suing if this profile is not down in 24 Hours.

**Comment by Gl1xzzy** [comment]
glixxzzy@gmail.com

**Comment by glixxzzy** [comment]
Excuse me, that is my client's email.
